INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (0,'Bruchia vogesiaca','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (1,'Petalophyllum ralfsii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (2,'Marsilea batardae','Trevo-de-quatro-folhas');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (3,'Salix salvifolia ssp. australis','Salgueiro-branco');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (4,'Dianthus cintranus ssp. cintranus','Cravo-de-Sintra');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (5,'Herniaria algarvica','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (6,'Herniaria lusitanica ssp. berlengiana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (7,'Silene rothmaleri','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (8,'Dianthus marizii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (9,'Jonopsidium acaule','Alfavaca-dos-montes');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (10,'Alyssum pintodasilvae','cicuta verde');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (11,'Dorycnium pentaphyllum ssp. transmontanum','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (12,'Ononis hackelii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (13,'Euphorbia transtagana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (14,'Tuberaria major','Tuberaria');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (15,'Eryngium viviparum','Cardo-pequeno-das-dunas');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (16,'Apium repens','Alecrim do campo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (17,'Thorella verticillatinundata','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (18,'Armeria pseudarmeria','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (19,'Limonium lanceolatum','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (20,'Limonium multiflorum','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (21,'Armeria rouyana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (22,'Armeria berlengensis','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (23,'Convolvulus fernandesii','Corriola do Espichel');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (24,'Myosotis lusitanica','Miosótis');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (25,'Myosotis retusifolia','Miosótis');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (26,'Omphalodes kuzinskyanae','Miosótis-das-praias');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (27,'Thymus carnosus','Tomilho-vulgar');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (28,'Thymus lotocephalus','Tomilho-cabeçudo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (29,'Thymus camphoratus','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (30,'Linaria ricardoi','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (31,'Linaria coutinhoi','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (32,'Linaria ficalhoana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (33,'Antirrhinum lopesianum','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (34,'Anarrhinum longipedicelatum','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (35,'Linaria algarviana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (36,'Verbascum litigiosum','Verbasco-de-flores-grossas');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (37,'Veronica micrantha','Verónicas');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (38,'Plantago algarbiensis','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (39,'Plantago almogravensis','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (40,'Jasione crispa ssp. serpentinica','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (41,'Jasione lusitanica','Campanula-lusitanica');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (42,'Senecio lagascanus ssp. lusitanicus','Erva-loira-da-boa-viagem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (43,'Santolina semidentata','Abrótano');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (44,'Santolina impressa','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (45,'Picris willkommii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (46,'Centaurea rothmalerana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (47,'Leuzea longifolia','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (48,'Doronicum plantagineum ssp. tournefortii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (49,'Leuzea rhaponticoides','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (50,'Asphodelus bento-rainhae','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (51,'Hyacinthoides vincentina','Jacinto-selvagem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (52,'Narcissus pseudonarcissus ssp. nobilis','Narciso');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (53,'Narcissus humilis','Narciso');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (54,'Narcissus fernandesii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (55,'Narcissus cyclamineus','Narciso-trombeta');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (56,'Narcissus scaberulus','Narciso');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (57,'Juncus valvatus','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (58,'Pseudarrhenatherum pallens','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (59,'Festuca brigantina','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (60,'Festuca elegans','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (61,'Festuca duriotagana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (62,'Festuca henriquesii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (63,'Festuca summilusitana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (64,'Holcus setiglumis ssp. duriensis','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (65,'Crepis pusilla','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (66,'Bryoerythrophyllum campylocarpum',' ');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (67,'Marsupella profunda','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (68,'Culcita macrocarpa','Feto-do-cabelinho');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (69,'Asplenium hemionitis','feto-folha-de-hera e feto-de-três-bicos');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (70,'Woodwardia radicans','Feto-de-botão e Feto-vaqueiro');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (71,'Silene longicilia','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (72,'Herniaria maritima','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (73,'Malcolmia lacera ssp. gracilima','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (74,'Murbeckiella sousae','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (75,'Rhynchosinapis erucastrum ssp. cintrana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (76,'Diplotaxis vicentina','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (77,'Iberis procumbens ssp. microcarpa','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (78,'Murbeckiella pinnatifida ssp. herminii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (79,'Biscutella vincentina','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (80,'Arabis sadina','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (81,'Saxifraga cintrana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (82,'Ulex densus','Tojo-da-charneca, tojo-gatunho e tojo-gatunha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (83,'Anthyllis lusitanica','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (84,'Melilotus segetalis ssp. fallax','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (85,'Thymelaea broterana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (86,'Cistus palhinhae','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (87,'Halimium verticillatum','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (88,'Armeria sampaioi','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (89,'Gentiana lutea','Genciana');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (90,'Teucrium salviastrum ssp. salviastrum','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (91,'Thymus capitellatus','Tomilho-do-mato');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (92,'Thymus villosus ssp. villosus','Tomilho-peludo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (93,'Scrophularia grandiflora ssp. grandiflora','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (94,'Scrophularia herminii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (95,'Chaenorhinum serpyllifolium ssp. lusitanicum','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (96,'Scrophularia sublyrata','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (97,'Arnica montana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (98,'Senecio caespitosus','Erva-loira');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (99,'Centaurea vicentina','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (100,'Centaurea micrantha ssp. herminii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (101,'Scilla beirana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (102,'Bellevalia hackelii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (103,'Scilla odorata','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (104,'Ruscus aculeatus','Gilbardeira');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (105,'Narcissus calcicola','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (106,'Narcissus bulbocodium','Campainhas-amarelas-do-monte');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (107,'Narcissus asturiensis','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (108,'Iris boissieri','Lírio do Monte');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (109,'Iris lusitanica','Lírio-amarelo-do-monte');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (110,'Avenula hackelii','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (111,'Spiranthes aestivalis','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (112,'Narcissus triandrus','Narciso');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (113,'Lycopodium clavatum','Licopódio');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (114,'Lycopodiella cernua','Pinheirinho, Musgão e Musgo do Mato');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (115,'Lycopodiella inundata','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (116,'Trichomanes speciosum','Feto-frisado');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (117,'Cladonia spp. (subgenus Cladina)',' ');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (118,'Macromia splendens','Libelinha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (119,'Oxygastra curtisii','Libélula ou Libelinha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (120,'Coenagrion mercuriale','Libelinha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (121,'Gomphus graslinii','Libélula ou Libelinha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (122,'Euphydryas aurinia','Fritilária-dos-lameiros');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (123,'Proserpinus proserpina',' ');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (124,'Callimorpha quadripunctaria','Borboleta');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (125,'Lucanus cervus','Cabra-loura, Vaca-loura, Carocha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (126,'Apteromantis aptera',' ');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (127,'Cerambyx cerdo','Longicórnio, Capricórnio-das-quercíneas, Rosca ou Larva-da-madeira');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (128,'Macrothele calpeiana','Não tem');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (129,'Unio tumidiformis','Mexilhão-de-rio do sul ou Náiade do Sul');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (130,'Margaritifera margaritifera','Mexilhão-de-rio ou Naiáde do Norte');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (131,'Geomalacus maculosus','Lesma');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (132,'Petromyzon marinus','Lampreia-marinha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (133,'Lampetra planeri','Lampreia-de-riacho');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (134,'Lampetra fluviatilis','Lampreia-de-rio');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (135,'Alosa fallax','Savelha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (136,'Chondrostoma polylepis','Boga-comum');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (137,'Rutilus alburnoides','Bordalo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (138,'Rutilus lemmingii','Boga-de-boca-arqueada');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (139,'Rutilus arcasii','Panjorca');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (140,'Chondrostoma lusitanicum','Boga-portuguesa');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (141,'Anaecypris hispanica','Saramugo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (142,'Rutilus macrolepidotus','Ruivaco');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (143,'Barbus comizo','Cumba');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (144,'Barbus bocagei','Barbo-comum');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (145,'Barbus microcephalus','Barbo-de-cabeça-pequena');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (146,'Barbus sclateri','Barbo do Sul');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (147,'Barbus steindachneri','Barbo de Steindachner');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (148,'Chondrostoma willkommii','Boga do Guadiana');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (149,'Chondrostoma almacai','Boga do Sudoeste');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (150,'Chondrostoma duriense','Boga do Norte');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (151,'Cobitis paludica','Verdemã-comum');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (152,'Cobitis calderoni','Verdemã do Norte');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (153,'Alosa alosa','Sável');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (154,'Chioglossa lusitanica','Salamandra-lusitânica');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (155,'Triturus marmoratus','Tritão-marmorado');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (156,'Alytes obstetricans','Sapo-parteiro-comum');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (157,'Alytes cisternasii','Sapo-parteiro-ibérico');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (158,'Discoglossus galganoi','Rã-de-focinho-ponteagudo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (159,'Pelobates cultripes','Sapo-de-unha-negra');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (160,'Bufo calamita','Sapo-corredor');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (161,'Hyla arborea','Rela-comum');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (162,'Hyla meridionalis','Rela-meridional');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (163,'Rana perezi','Rã-verde');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (164,'Rana iberica','Rã-ibérica');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (165,'Emys orbicularis','Cágado-de-carapaça-estriada');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (166,'Mauremys leprosa','Cágado-mediterrânico');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (167,'Lacerta monticola','Largartixa-da-montanha');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (168,'Lacerta schreiberi','Lagarto-de-água');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (169,'Chalcides bedriagai','Cobra-de-pernas-pentadáctila');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (170,'Coronella austriaca','Cobra-lisa-europeia');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (171,'Coluber hippocrepis','Cobra-de-ferradura');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (172,'Vipera seoanei','Víbora-de-Seoanei');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (173,'Rhinolophus mehelyi','Morcego-de-ferradura-mourisco');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (174,'Rhinolophus hipposideros','Morcego-de-ferradura-pequeno');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (175,'Rhinolophus ferrumequinum','Morcego-de-ferradura-grande');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (176,'Rhinolophus euryale','Morcego-de-ferradura-mediterrânico');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (177,'Myotis blythii','Morcego-rato-pequeno');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (178,'Barbastella barbastellus','Morcego-negro');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (179,'Pipistrellus pipistrellus','Morcego-anão');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (180,'Miniopterus schreibersii','Morcego-de-peluche');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (181,'Myotis daubentonii','Morcego-de-água');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (182,'Myotis emarginatus','Morcego-lanudo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (183,'Myotis nattereri','Morcego-de-franja');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (184,'Myotis bechsteinii','Morcego de Bechstein');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (185,'Myotis myotis','Morcego-rato-grande');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (186,'Plecotus auritus','Morcego-orelhudo-castanho');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (187,'Eptesicus serotinus','Morcego-hortelão-escuro');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (188,'Nyctalus lasiopterus','Morcego-arborícola-gigante');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (189,'Myotis mystacinus','Morcego-de-bigodes');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (190,'Tadarida teniotis','Morcego-rabudo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (191,'Pipistrellus pygmaeus','Morcego-pigmeu');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (192,'Hypsugo savii','Morcego de Savii');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (193,'Canis lupus','Lobo Ibérico');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (194,'Galemys pyrenaicus','Toupeira-de-água');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (195,'Microtus cabrerae','Rato de Cabrera');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (196,'Lutra lutra','Lontra');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (197,'Martes martes','Marta');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (198,'Herpestes ichneumon','Sacarrabos');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (199,'Felis silvestris','Gato-bravo');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (200,'Capra pyrenaica','Cabra-montês');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (201,'Mustela putorius','Toirão');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (202,'Genetta genetta','Geneta');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (203,'Plecotus austriacus','Morcego-orelhudo-cinzento');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (204,'Nyctalus leisleri','Morcego-arborícola-pequeno');
INSERT INTO species (specieID, scientificName, nomevulgar) VALUES (205,'Pipistrellus kuhlii','Morcego de Kuhl');
